@startuml
    namespace SuperEasyShare.app {

        class Main [[Main.html]] {
            {static} -cars: Car[]
            {static} -customers: Customer[]
            {static} -rates: Rate[]
            {static} -trips: Trip[]
            {static} +main(String[]): void
            {static} -tabularPrint(Trip[]): void
        }

    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
