@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    abstract class "<size:14>Rate\n<size:10>SuperEasyShare.entities" as SuperEasyShare.entities.Rate [[Rate.html]] {
        {abstract} +total(Trip): int
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
