@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Trip\n<size:10>SuperEasyShare.entities" as SuperEasyShare.entities.Trip [[Trip.html]] {
        -car: Car
        -renter: Customer
        -rate: Rate
        -startTime: DateTime
        -endTime: DateTime
        -status: TripStatus
        -distance: double
        +Trip(Car, Customer, Rate)
        +Trip(Car, Customer, Rate, DateTime)
        +Trip(Car, Customer, Rate, DateTime, DateTime, double)
        +Trip(Trip)
        +start(DateTime): Trip
        +end(DateTime, double): Trip
        +total(): int
        +getStartTime(): DateTime
        +getEndTime(): DateTime
        +getDistance(): double
        +getStatus(): TripStatus
        +getRate(): Rate
        +duration(): int
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
