@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>Customer\n<size:10>SuperEasyShare.provided" as SuperEasyShare.provided.Customer [[Customer.html]] {
        -name: String
        +Customer(String)
        +Customer(Customer)
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
