@startuml
    namespace SuperEasyShare.provided {

        class Car [[Car.html]] {
            -make: String
            -model: String
            -registration: String
            +Car()
            +Car(Car)
            +Car(String, String, String)
            +setMake(String): void
            +setModel(String): void
            +setRegistration(String): void
        }

        class DateTime [[DateTime.html]] {
            ~day: int
            ~month: int
            ~year: int
            ~hr: int
            ~min: int
            +DateTime(int, int, int, int, int)
            +DateTime(DateTime)
            +compareTo(DateTime): int
            +ts(): long
            -uts(): long
            +diff(DateTime): long
        }

        enum TripStatus [[TripStatus.html]] {
            {static} +CREATED
            {static} +STARTED
            {static} +COMPLETED
        }

        class Customer [[Customer.html]] {
            -name: String
            +Customer(String)
            +Customer(Customer)
        }

        java.lang.Comparable <|.. DateTime
    }

    namespace java.lang {
        interface Comparable<T> {
            {abstract} +compareTo(T): int
        }
    }

    center footer UMLDoclet 2.1.0, PlantUML %version()
@enduml
